stages:
  - validate
# - test

style_check:
  stage: validate
  image: sensirion/embedded-ci:2.2.0
  tags: [linux, docker]
  script:
    - clang-format-7 -i SensiGadgetHub/*
    - git diff --exit-code

# compile_test:
#     stage: test
#     image:
#         name: registry.gitlab.sensirion.lokal/sensirion/docker/docker-arduino:0.5.0
#     tags: [docker, linux]
#     needs: []
#     script:
#         - ls
#         - arduino-cli update
#         - export ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL=true
#         - arduino-cli lib install "NimBLE-Arduino@1.4.0"
#         - ln -s $PWD ~/Arduino/libraries/
#         - git clone https://github.com/Xinyuan-LilyGO/TTGO-T-Display
#         - arduino-cli lib install --git-url https://github.com/MBjoern/arduino-ble-sensiscan
#         - ln -s $PWD/TTGO-T-Display/TFT_eSPI ~/Arduino/libraries/TFT_eSPI
#         - cp $PWD/resources/fonts/* ~/Arduino/libraries/TFT_eSPI/Fonts/Custom/
#         - cp $PWD/resources/User_Custom_Fonts.h ~/Arduino/libraries/TFT_eSPI/User_Setups/
#         - arduino-cli compile --warnings all --build-cache-path tmp --fqbn esp32:esp32:esp32 SensiGadgetHub/SensiGadgetHub.ino
